### PR TITLE
fix: moved the example project creation to a separate file

### LINKED ISSUE #3: Change how example projects are handled
Presently, changing the example projects which are built requires manual editing of the '/premake/premake5.lua' file.

It would make more sense (and be more convenient) if the example project(s) were handled in a similar manner to the vendor libraries... that is, why not just throw an '/examples/premake5.lua' file into the '/examples/' directory?

In this situation, editing the example projects which are built would still require editing _a_ 'premake5.lua' file but now it would be better organized!

In fact, making use of wildcard matching in the main 'premake5.lua' file could allow for nested directories inside the '/examples/' directory, each with their own '/premake/premake5.lua' subdirectory! To be as flexible as possible, this is the approach that should be implemented!

### PR DESCRIPTION
**Pull request by sherwoodben**
Closes  #3.

Super easy fix!

### CODE REVIEW

File: premake/premake5.lua [hunk 1]
```diff
@@ -62,24 +62,6 @@ function project_filters()
     ]]
 end
 
-function make_examples()
```
Comment (sherwoodben) [inline premake/premake5.lua:65]: There was no need to have this as a separate function when we could just include a separate examples premake5.lua file!

File: premake/premake5.lua [hunk 2]
```diff
@@ -696,7 +678,7 @@ function build_workspace_and_projects()
   group "Examples"
   if (string.lower(cv.buildExamples[1]) == "true") then
     printf("Configuring example application(s).")
-    make_examples()
+    include("../examples/premake/")
```
Comment (sherwoodben) [inline premake/premake5.lua:681]: use the 'include' function instead of a custom 'make_examples' function

File: examples/premake/premake5.lua
Comment (sherwoodben) [inline examples/premake/premake5.lua:1]: Added initial file contents

**Review by sherwoodben — COMMENTED** [review]
Should be good to go!
